# from django.forms import NullBooleanField
# import requests

# url = "http://apiclient.besoccerapps.com/scripts/api/api.php?key={&tz=Europe/Madrid&format=json&req=player&id=28185"

# payload={}
# headers = {}

# response = requests.request("GET", url, headers=headers, data=payload)

# print(response.text)





# {
#   "player_id": "74892",
#   "nick": "Carvajal",
#   "name": "Daniel",
#   "last_name": "Carvajal Ramos",
#   "role": "2",
#   "country": "España",
#   "birthdate": "1992-01-11",
#   "age": "31",
#   "CountryCode": "es",
#   "CountryCode2": "ES",
#   "CountryCode3": "",
#   "weight": "70",
#   "height": "173",
#   "twitter": "@DaniCarvajal92",
#   "website": NullBooleanField,
#   "contract_start": "2013-07-01",
#   "contract_end": "2025-06-30",
#   "pos1": "RB",
#   "pos2": "RWB",
#   "pos3": "LB",
#   "foot": "1",
#   "squad_number": "2",
#   "year": "2023",
#   "goals_conceded": "0",
#   "competition_name": "La Liga",
#   "competition_logo": "https://t.resfu.com/media/img/league_logos/primera.png?size=60x",
#   "table_suffix": null,
#   "team_name": "Real Madrid",
#   "basealias": "real-madrid",
#   "team_id": "2107",
#   "player_avatar": "https://t.resfu.com/img_data/players/original/74892.jpg?size=180x&lossy=1&v=28",
#   "team_shield": "https://t.resfu.com/img_data/escudos/medium/2107.jpg?size=40x&lossy=1&v=28",
#   "country_flag": "https://t.resfu.com/media/img/flags/st3/large/es.png?size=100x65c&lossy=1&v=28",
#   "statistics_resume": [
#     {
#       "year": "2023",
#       "squadNumber": "2",
#       "league_id": "67669",
#       "team_id": "2107",
#       "team_name": "Real Madrid",
#       "basealias": "real-madrid",
#       "category_id": "1",
#       "category_name": "Primera División",
#       "category_alias": "primera",
#       "category_logo": "https://t.resfu.com/media/img/league_logos/primera.png?size=60x",
#       "country_alias": "espana",
#       "country_name": "España",
#       "goals_conceded": 0,
#       "group_code": "1",
#       "total_group": "1",
#       "games_played": 20,
#       "minutes_played": 1366,
#       "reserved": 5,
#       "yellow_cards": 4,
#       "red_cards": 0,
#       "assists": 2,
#       "lineups": "15",
#       "goals": 0
#     },
#     {
#       "year": "2023",
#       "squadNumber": "2",
#       "league_id": "68817",
#       "team_id": "2107",
#       "team_name": "Real Madrid",
#       "basealias": "real-madrid",
#       "category_id": "107",
#       "category_name": "Champions League",
#       "category_alias": "champions",
#       "category_logo": "https://t.resfu.com/media/img/league_logos/champions.png?size=60x",
#       "country_alias": "competiciones_europeas",
#       "country_name": "Competiciones Europeas",
#       "goals_conceded": 0,
#       "group_code": "6",
#       "total_group": "8",
#       "games_played": 6,
#       "minutes_played": 445,
#       "reserved": 1,
#       "yellow_cards": 1,
#       "red_cards": 0,
#       "assists": 2,
#       "lineups": "5",
#       "goals": 0
#     },
#     {
#       "year": "2023",
#       "squadNumber": "20",
#       "league_id": "66205",
#       "team_id": "3850",
#       "team_name": "España",
#       "basealias": "seleccion-espanola",
#       "category_id": "2006",
#       "category_name": "Liga de las Naciones de la UEFA",
#       "category_alias": "liga_de_las_naciones_de_la_uefa",
#       "category_logo": "https://t.resfu.com/media/img/league_logos/nations_league.png?size=60x",
#       "country_alias": "competiciones_europeas",
#       "country_name": "Competiciones Europeas",
#       "goals_conceded": 0,
#       "group_code": "1",
#       "total_group": "5",
#       "games_played": 3,
#       "minutes_played": 270,
#       "reserved": 0,
#       "yellow_cards": 2,
#       "red_cards": 0,
#       "assists": 0,
#       "lineups": "3",
#       "goals": 0
#     },
#     {
#       "year": "2023",
#       "squadNumber": "2",
#       "league_id": "70815",
#       "team_id": "2107",
#       "team_name": "Real Madrid",
#       "basealias": "real-madrid",
#       "category_id": "137",
#       "category_name": "Mundial de Clubes",
#       "category_alias": "mundial_clubes",
#       "category_logo": "https://t.resfu.com/media/img/league_logos/mundial-clubes.png?size=60x",
#       "country_alias": "internacional",
#       "country_name": "Internacional",
#       "goals_conceded": 0,
#       "group_code": "0",
#       "total_group": "1",
#       "games_played": 1,
#       "minutes_played": 80,
#       "reserved": 0,
#       "yellow_cards": 0,
#       "red_cards": 0,
#       "assists": 1,
#       "lineups": "1",
#       "goals": 0
#     },
#     {
#       "year": "2023",
#       "squadNumber": "2",
#       "league_id": "69563",
#       "team_id": "2107",
#       "team_name": "Real Madrid",
#       "basealias": "real-madrid",
#       "category_id": "129",
#       "category_name": "Copa del Rey",
#       "category_alias": "copa_del_rey",
#       "category_logo": "https://t.resfu.com/media/img/league_logos/copa_del_rey.png?size=60x",
#       "country_alias": "espana",
#       "country_name": "España",
#       "goals_conceded": 0,
#       "group_code": "0",
#       "total_group": "1",
#       "games_played": 1,
#       "minutes_played": 90,
#       "reserved": 0,
#       "yellow_cards": 0,
#       "red_cards": 0,
#       "assists": 0,
#       "lineups": "1",
#       "goals": 0
#     },
#     {
#       "year": "2023",
#       "squadNumber": "2",
#       "league_id": "67711",
#       "team_id": "2107",
#       "team_name": "Real Madrid",
#       "basealias": "real-madrid",
#       "category_id": "133",
#       "category_name": "Supercopa Europa",
#       "category_alias": "supercopa_europa",
#       "category_logo": "https://t.resfu.com/media/img/league_logos/supercopa_europa.png?size=60x",
#       "country_alias": "competiciones_europeas",
#       "country_name": "Competiciones Europeas",
#       "goals_conceded": 0,
#       "group_code": "0",
#       "total_group": "1",
#       "games_played": 1,
#       "minutes_played": 85,
#       "reserved": 0,
#       "yellow_cards": 0,
#       "red_cards": 0,
#       "assists": 0,
#       "lineups": "1",
#       "goals": 0
#     },
#     {
#       "year": "2023",
#       "squadNumber": "2",
#       "league_id": "67728",
#       "team_id": "2107",
#       "team_name": "Real Madrid",
#       "basealias": "real-madrid",
#       "category_id": "132",
#       "category_name": "Supercopa de España",
#       "category_alias": "supercopa",
#       "category_logo": "https://t.resfu.com/media/img/league_logos/supercopa_espana.png?size=60x",
#       "country_alias": "espana",
#       "country_name": "España",
#       "goals_conceded": 0,
#       "group_code": "0",
#       "total_group": "1",
#       "games_played": 2,
#       "minutes_played": 94,
#       "reserved": 1,
#       "yellow_cards": 0,
#       "red_cards": 0,
#       "assists": 0,
#       "lineups": "1",
#       "goals": 0
#     },
#     {
#       "year": "2023",
#       "squadNumber": "2",
#       "league_id": "67829",
#       "team_id": "2107",
#       "team_name": "Real Madrid",
#       "basealias": "real-madrid",
#       "category_id": "2633",
#       "category_name": "Soccer Champions Tour",
#       "category_alias": "soccer-champions-tour",
#       "category_logo": "https://t.resfu.com/media/img/league_logos/soccer_champ_tour.png?size=60x",
#       "country_alias": "internacional",
#       "country_name": "Internacional",
#       "goals_conceded": 0,
#       "group_code": "1",
#       "total_group": "1",
#       "games_played": 1,
#       "minutes_played": 63,
#       "reserved": 0,
#       "yellow_cards": 0,
#       "red_cards": 0,
#       "assists": 0,
#       "lineups": "1",
#       "goals": 0
#     },
#     {
#       "year": "2023",
#       "squadNumber": "20",
#       "league_id": "68172",
#       "team_id": "3850",
#       "team_name": "España",
#       "basealias": "seleccion-espanola",
#       "category_id": "1986",
#       "category_name": "Amistosos Selecciones No Oficiales",
#       "category_alias": "amistosos_selecciones_no_reconocidas",
#       "category_logo": "https://t.resfu.com/media/img/league_logos/amistoso.png?size=60x",
#       "country_alias": "internacional",
#       "country_name": "Internacional",
#       "goals_conceded": 0,
#       "group_code": "1",
#       "total_group": "1",
#       "games_played": 1,
#       "minutes_played": 46,
#       "reserved": 0,
#       "yellow_cards": 0,
#       "red_cards": 0,
#       "assists": 0,
#       "lineups": "1",
#       "goals": 0
#     }
#   ],
#   "hasNews": true,
#   "injured": []
# }