version: '3'

services:
  web:
    image: fl-django
    command: gunicorn football_quiz.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - celery
    working_dir: /code  # Cambia el directorio de trabajo dentro del contenedor
#    volumes:
#      - .:/code  # Monta el directorio actual en /app dentro del contenedor

  celery:
    image: fl-django
    command: celery -A football_quiz worker -l info
    depends_on:
      - redis
#    volumes:
#      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=football_quiz.settings

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"