# Generated by Django 4.1.12 on 2023-11-13 21:30

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('year', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.IntegerField()),
                ('total_group', models.IntegerField()),
                ('round', models.IntegerField()),
                ('local', models.CharField(blank=True, max_length=25, null=True)),
                ('visitor', models.CharField(blank=True, max_length=25, null=True)),
                ('league_id', models.IntegerField()),
                ('stadium', models.CharField(blank=True, max_length=255, null=True)),
                ('team1', models.IntegerField()),
                ('team2', models.IntegerField()),
                ('conference', models.IntegerField()),
                ('dteam1', models.IntegerField()),
                ('dteam2', models.IntegerField()),
                ('numc', models.IntegerField()),
                ('no_hour', models.BooleanField(default=False)),
                ('local_abbr', models.CharField(blank=True, max_length=3, null=True)),
                ('visitor_abbr', models.CharField(blank=True, max_length=3, null=True)),
                ('competition_name', models.CharField(blank=True, max_length=25, null=True)),
                ('competition_id', models.IntegerField()),
                ('split_league', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('type_id', models.IntegerField()),
                ('playoffs', models.BooleanField(default=False)),
                ('group_code', models.IntegerField()),
                ('total_rounds', models.IntegerField()),
                ('coef', models.FloatField()),
                ('cflag_local', models.URLField()),
                ('cflag_visitor', models.URLField()),
                ('local_shield', models.URLField()),
                ('visitor_shield', models.URLField()),
                ('extraTxt', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule', models.DateTimeField()),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('local_goals', models.IntegerField()),
                ('visitor_goals', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('live_minute', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('channels', djongo.models.fields.JSONField()),
                ('winner', models.CharField(blank=True, max_length=10, null=True)),
                ('penaltis1', models.IntegerField(blank=True, null=True)),
                ('penaltis2', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('coins', models.IntegerField(default=1000)),
                ('rating', models.IntegerField(default=1200)),
                ('country', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('membership', models.CharField(choices=[('F', 'Free'), ('P', 'Premium'), ('P+', 'Premium+')], default='F', max_length=2)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
                'permissions': [('view_history', 'Can view history')],
            },
        ),
    ]
