# Generated by Django 4.1.12 on 2023-11-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthMatches',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team1', models.IntegerField()),
                ('team2', models.IntegerField()),
                ('r1', models.SmallIntegerField()),
                ('r2', models.SmallIntegerField()),
                ('p1', models.IntegerField()),
                ('p2', models.IntegerField()),
                ('status', models.IntegerField()),
                ('round', models.IntegerField()),
                ('schedule', models.DateTimeField()),
                ('league_id', models.IntegerField()),
                ('t1', models.CharField(max_length=20)),
                ('t2', models.CharField(max_length=20)),
                ('id_t1', models.IntegerField()),
                ('id_t2', models.IntegerField()),
                ('finished', models.SmallIntegerField()),
                ('t1_short', models.CharField(max_length=3)),
                ('t2_short', models.CharField(max_length=3)),
                ('group_code', models.SmallIntegerField()),
                ('categoryId', models.SmallIntegerField()),
                ('year', models.IntegerField()),
                ('cc1', models.CharField(max_length=2)),
                ('cc2', models.CharField(max_length=2)),
            ],
        ),
    ]
