# Generated by Django 4.1.12 on 2023-10-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
