# Generated by Django 4.1.12 on 2023-11-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
