# Generated by Django 4.1.12 on 2023-12-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='id',
        ),
        migrations.AlterField(
            model_name='stats',
            name='player_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
