# Generated by Django 4.1.12 on 2023-10-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classification_type_classification_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
