# Generated by Django 4.1.12 on 2023-10-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_classification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('group', models.IntegerField()),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('conference', models.IntegerField()),
                ('team', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('shield', models.URLField(blank=True, null=True)),
                ('cflag', models.URLField(blank=True, null=True)),
                ('basealias', models.CharField(max_length=255)),
                ('gf', models.IntegerField(blank=True, null=True)),
                ('ga', models.IntegerField(blank=True, null=True)),
                ('avg', models.IntegerField()),
                ('matchs_coef', models.CharField(blank=True, max_length=255, null=True)),
                ('points_coef', models.CharField(blank=True, max_length=255, null=True)),
                ('coef', models.CharField(blank=True, max_length=255, null=True)),
                ('coefficients', models.CharField(blank=True, max_length=255, null=True)),
                ('mark', models.CharField(blank=True, max_length=255, null=True)),
                ('class_mark', models.CharField(blank=True, max_length=255, null=True)),
                ('round', models.IntegerField()),
                ('pos', models.IntegerField()),
                ('countrycode', models.CharField(max_length=4)),
                ('abbr', models.CharField(max_length=10)),
                ('form', models.CharField(max_length=15)),
                ('direction', models.CharField(blank=True, max_length=200)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'ordering': ['pos'],
            },
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
    ]
