# Generated by Django 4.1.12 on 2023-10-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_classification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='type',
            field=models.CharField(blank=True, choices=[('campeon', 'Campeón'), ('cha', 'Champions League'), ('uefa', 'Europa League'), ('regular', 'laliga'), ('elimconf', 'Fase Eliminatoria Conference League'), ('desc', 'Descenso')], max_length=40, null=True),
        ),
    ]
